name: HACS Action

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
